INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Robert Downey, Jr'); 
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Samuel L. Jackson');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Paul Bettany');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Chris Hemsworth');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Tom Hiddleston');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Scarlett Johansson');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Mark Ruffalo');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Don Cheadle');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Bradley Cooper');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Cobie Smulders');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Jaimie Alexander');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Evangeline Lilly');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Jon Favreau');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Chris Evans');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Gwyneth Paltrow');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Sebastian Stan');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Benedict Wong');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Hayley Atwell');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Dave Bautista');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Benedict Cumberbatch');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Vin Diesel');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Idris Elba');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Karen Gillan');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Clark Gregg');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Chris Pratt');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Jeremy Renner');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Cobie Smulders');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Jacob Batalon');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('William Hurt');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Florence Kasumba');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Pom Klementieff');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Paul Rudd');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Stellan Skarsgård');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Marisa Tomei');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Chadwick Boseman');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Josh Brolin');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Kat Dennings');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Micheal Douglas');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Winston Duke');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Danai Gurira');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Brie Larson');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Natalie Portman');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Zoe Saldana');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('John Slattery');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Letitia Wright');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Tadanobu Asano');
INSERT INTO `final-project`.`actor` (`actor_name`) VALUES ('Angela Bassett');


INSERT INTO `final-project`.`rating` (`movie_rating`, `rating_description`) VALUES ('G', 'General Audience');
INSERT INTO `final-project`.`rating` (`movie_rating`, `rating_description`) VALUES ('PG', 'Parental Guidance Suggested');
INSERT INTO `final-project`.`rating` (`movie_rating`, `rating_description`) VALUES ('PG-13', 'Parents Strongly Cautioned');
INSERT INTO `final-project`.`rating` (`movie_rating`, `rating_description`) VALUES ('R', 'Restricted');
INSERT INTO `final-project`.`rating` (`movie_rating`, `rating_description`) VALUES ('NC-17', 'No One 17 and Under Admitted');
INSERT INTO `final-project`.`rating` (`movie_rating`, `rating_description`) VALUES ('NR', 'Not Yet Rated');

INSERT INTO `final-project`.`movie` (`movie_title`, `rating_id`) VALUES ('Captain America: The First Avenger', '3');
INSERT INTO `final-project`.`movie` (`movie_title`, `rating_id`) VALUES ('Captain Marvel', '3');
INSERT INTO `final-project`.`movie` (`movie_title`, `rating_id`) VALUES ('Thor: The Dark World', '3');
INSERT INTO `final-project`.`movie` (`movie_title`, `rating_id`) VALUES ('Avengers: Age of Ultron', '3');
INSERT INTO `final-project`.`movie` (`movie_title`, `rating_id`) VALUES ('Doctor Strange', '3');
INSERT INTO `final-project`.`movie` (`movie_title`, `rating_id`) VALUES ('Shang-Chi and the Legend of the Ten Rings', '3');
INSERT INTO `final-project`.`movie` (`movie_title`, `rating_id`) VALUES ('Thor: Love and Thunder', '3');
INSERT INTO `final-project`.`movie` (`movie_title`, `rating_id`) VALUES ('Iron Man', '3');
INSERT INTO `final-project`.`movie` (`movie_title`, `rating_id`) VALUES ('Iron Man 2', '3');
INSERT INTO `final-project`.`movie` (`movie_title`, `rating_id`) VALUES ('The Incredible Hulk', '3');

INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('1', '1');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('2', '1');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('3', '1');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('4', '1');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('5', '2');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('6', '2');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('7', '2');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('8', '2');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('9', '3');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('10', '3');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('11', '3');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('12', '3');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('13', '4');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('14', '4');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('15', '4');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('16', '4');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('17', '5');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('18', '5');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('19', '5');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('20', '5');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('21', '6');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('22', '6');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('23', '6');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('24', '6');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('25', '7');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('26', '7');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('27', '7');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('28', '7');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('29', '8');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('30', '8');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('31', '8');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('32', '8');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('33', '9');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('34', '9');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('35', '9');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('36', '9');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('37', '10');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('38', '10');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('39', '10');
INSERT INTO `final-project`.`cast` (`actor_id`, `movie_id`) VALUES ('40', '10');
